/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MedicamentsForm: typeof import('./src/components/MedicamentsForm.vue')['default']
    MedicamentsHeader: typeof import('./src/components/MedicamentsHeader.vue')['default']
    MedicamentsList: typeof import('./src/components/MedicamentsList.vue')['default']
    MedicamentsListItem: typeof import('./src/components/MedicamentsListItem.vue')['default']
    MedicamentsSearch: typeof import('./src/components/MedicamentsSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
